<div class="row header">
    <div class="col-3 col-sm-2">
        <a id="toggle-form" href="#" class="btn btn-light fa fa-plus-circle fa-2x"
           rel="tooltip" title="{|toggle_form|}"></a>
    </div>
    <div class="col text-center user">
        <span class="d-sm-none">{{echo App\User::$name}}</span>
        <span class="d-none d-sm-inline h2">{{echo App\User::$name}}</span>
        <form method="post">
            <button type="submit" class="btn btn-light" rel="tooltip" title="{|logout|}"
                    name="action" value="logout">
                <i class="fa fa-sign-out-alt"></i>
            </button>
        </form>
    </div>
    <div class="col-3 col-sm-2 text-right">
        <a href="/" class="btn btn-light fa fa-sync fa-2x" rel="tooltip" title="{|reload_page|}"></a>
    </div>
</div>

<!-- Add auctions form start, show if no sniping group is defined yet -->
<form method="post" accept-charset="utf-8">
    <input id="name_old" type="hidden" name="name_old" value="{{if (isset($snipe)) echo $snipe->name}}">

    <div id="add-form" class="row {{if (count($snipes) && !isset($snipe)) echo 'd-none'}}">
        <div class="col">
            <hr>
            <div class="form-group row">
                <div class="col-sm-3">
                    <label class="col-form-label" for="name">{|group_name|}</label>
                    <small class="form-text text-muted d-sm-none mb-1">{|group_hint|}</small>
                </div>
                <div class="col">
                    <input type="text" id="name" class="form-control" name="name"
                           required>
                    <small class="form-text text-muted d-none d-sm-block">{|group_hint|}</small>
                </div>
            </div>

            <div class="form-group row">
                <div class="col-sm-3">
                    <label class="col-form-label" for="data">{|auctions|}</label>
                    <small class="form-text text-muted d-sm-none mb-1">{|auction_hint|}</small>
                    <small class="form-text text-muted mb-1">
                        <a id="example" href="#">{|example|}</a>
                    </small>
                </div>
                <div class="col">
                    <textarea id="data" class="form-control" style="height:5rem"
                              name="data" required></textarea>
                    <small class="form-text text-muted d-none d-sm-block">{|auction_hint|}</small>
                </div>
            </div>

            <div class="row">
                <div class="col-sm-3"></div>
                <div class="col">
                    <div class="row">
                        <div class="col">
                            <button class="btn btn-primary btn-block" name="action"
                                    value="start">{|start|}</button>
                        </div>
                        <div class="col">
                            <button class="btn btn-secondary btn-block" name="action"
                                    value="save">{|save|}</button>
                        </div>
                    </div>
                </div>
            </div>
            <hr>
        </div>
    </div>

</form>

<!-- Sniping groups start-->
<div class="mt-3 px-3">
    {{foreach ($snipes as $snipe): $token = $snipe->getHash()}}
    <div class="row group table-bordered table-{{echo $snipe->pid ? 'success' : 'secondary'}}">
        {{if (isset($_SESSION['new'][$snipe->getHash()])):}}
        <div class="col-auto name py-2 pr-0">
            <i class="fas fa-fw fa-exclamation-circle" style="color:green"></i>
        </div>
        {{endif}}
        <div class="col py-2">
            <span class="pointer name mr-2" rel="tooltip" title="{|show_log|}"
                  data-toggle="log" data-token="{{$token}}">
                {{$snipe->name}}
            </span>
            {{if ($snipe->end):}}
            <br>
            <small class="text-monospace">
                <i class="fas fa-fw fa-clock mr-1"></i> {{$snipe->end}}
            </small>
            {{elseif ($snipe->won):}}
            <div class="badge badge-pill badge-success align-text-bottom text-monospace"
                 rel="tooltip" title="{|won|}">
                <i class="fa fa-fw fa-shopping-bag pr-2"></i> {{$snipe->won}}
            </div>
            {{endif}}
        </div>
        <div class="col-auto text-right py-2 pr-2">
            <!-- Action buttons -->
            <form method="post">
                <input type="hidden" name="name" value="{{$snipe->name}}">

                <a href="#" data-api="edit" data-token="{{$token}}" class="btn btn-sm btn-primary mr-sm-2 mb-2 mb-sm-0"
                   rel="tooltip" title="{|edit_group|}" value="edit">
                    <i class="far fa-fw fa-edit"></i>
                </a>
                <br class="d-sm-none">
                <!-- esniper process IS running -->
                <button class="btn btn-sm btn-danger btn-stop {{if (!$snipe->pid):}}d-none{{endif}}"
                        name="action" data-api="stop" data-token="{{$token}}"
                        rel="tooltip" title="{|stop_snipe|}" value="stop">
                    <i class="fas fa-fw fa-stop"></i>
                </button>
                <!-- esniper process IS NOT running -->
                <button class="btn btn-sm btn-warning btn-delete {{if ($snipe->pid):}}d-none{{endif}}"
                        name="action" data-api="delete" data-token="{{$token}}"
                        rel="tooltip" title="{|remove_group|}" value="delete">
                    <i class="fas fa-fw fa-trash"></i>
                </button>

            </form>
        </div>
        <div class="col-12 log d-none px-0">
            <!-- esniper prtocol file -->
            <div class="pre p-2 mb-0" tabindex="-1">{{if ($snipe->log):}}{{$snipe->log}}{{else:}}{|no_log|}{{endif}}</div>
            {{if ($snipe->end):}}
            <a class="btn btn-sm btn-light m-2" data-api="log" data-token="{{$token}}"
               rel="tooltip" title="{|reload_log|}">
                <i class="fa fa-sync"></i>
            </a>
            {{endif}}
        </div>
    </div>
    {{endforeach}}
</div>
<!-- Sniping groups end -->

{{if (count($bugs)):}}
<div class="row mt-4">
    <div class="col">
        <div class="h2">esniper bug reports</div>

        <form method="post">

            {{foreach ($bugs as $bug):}}
            <div class="form-check">
                <input type="checkbox" class="form-check-input" name="bugs[]"
                       value="{{$bug}}">
                &nbsp;
                <a class="form-check-label" href="?api=bug&amp;bug={{$bug}}"
                   rel="tooltip" title="Show esniper bug report" target="_blank">
                    <i class="fa fa-fw fa-external-link-alt mr-1"></i>
                    {{$bug}}
                </a>
            </div>
            {{endforeach}}

            <button type="submit" class="btn btn-primary mt-3" name="action"
                    value="bug">
                <i class="fas fa-fw fa-trash"></i> &nbsp; Delete esniper bug
                report(s)
            </button>

        </form>
    </div>
</div>
{{endif}}

<footer class="footer my-5">
    <div class="row d-none d-sm-flex border-top pt-2">
        <div class="col">
            <img src="favicon.ico" class="mr-1" style="height:1rem;vertical-align:text-top;">
            Minimal esniper web frontend
            <br>
            <small>
                <strong class="text-monospace">v{{$config->version}}</strong>,
                check on
                <a href="https://github.com/K-Ko/MiniEsniperWebFrontend" class="mx-1"
                   target="_blank">
                    <i class="fab fa-github"></i> GitHub
                </a>
                for updates
            </small>
        </div>
        <div class="col text-right">
            <a href="http://esniper.sourceforge.net/" target="_blank">
                <i class="fa fa-external-link-alt"></i>
                {{$config->esniper_version}}
            </a>
            <br>
            <a href="javascript:(function(w, d) {
                let itemEl = d.getElementById('descItemNumber'),
                    item = itemEl ? itemEl.innerHTML : w.getSelection().toString();
                if (item) {
                    let name = prompt('{|group_name|}', d.title.replace(/\s*\|.*/, ''));
                    if (!name) return;
                    let priceEl = d.querySelectorAll('[itemprop=price]'),
                        price = priceEl ? priceEl[0].getAttribute('content') : '1.00',
                        bid = prompt('{|your_bid|}', price);
                    if (!bid) return;
                    let shipEl = d.getElementById('fshippingCost').getElementsByTagName('span'),
                        ship = shipEl ? shipEl[0].innerHTML : '',
                        e = encodeURIComponent;
                    w.open(
                        [   'http://{{$server_name}}?api=bookmark',
                            'token=' + e('{{$user_name}}'),
                            'item=' + e(item),
                            'name=' + e(name),
                            'price=' + e(price),
                            'ship=' + e(ship),
                            'bid=' + e(bid)
                        ].join('&'),
                        'mewf_popup',
                        'width=480,height=120,dialog,dependent,titlebar=0'
                    );
                } else {
                    w.alert('Can not detect item number, please help and select item number before!');
                }
            })(window, document);"
               class="small" rel="tooltip" title="{|bookmarklet_hint|}">
                {|bookmarklet|}
            </a>
            |
            <a href="/?login={{echo urlencode($_SESSION['token'])}}" class="small"
               rel="tooltip" title="{|bookmarklet_hint|}">
                {|token_login|}
            </a>
        </div>
    </div>
    <div class="row d-sm-none">
        <div class="col text-center">
            <a href="/?login={{echo urlencode($_SESSION['token'])}}" class="small"
               rel="tooltip" title="{|bookmarklet_hint|}">
                {|token_login|}
            </a>
        </div>
    </div>
</footer>
