<!--
/**
 * Main HTML file
 *
 * @author     Knut Kohl <github@knutkohl.de>
 * @copyright  (c) 2016 Knut Kohl
 * @licence    MIT License - http://opensource.org/licenses/MIT
 */
-->
<!DOCTYPE html>
<html lang="{{$config->language}}">

<head>
    <!-- https://tomitm.github.io/appmanifest/ -->
    <link rel="manifest" href="manifest.json">
    <meta name="mobile-web-app-capable" content="yes">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="application-name" content="MEF">
    <meta name="apple-mobile-web-app-title" content="MEF">
    <meta name="theme-color" content="#0F6DF6">
    <meta name="msapplication-navbutton-color" content="#0F6DF6">
    <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
    <meta name="msapplication-starturl" content="/">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="icon" type="image/ico" sizes="64x64" href="favicon.ico">
    <link rel="apple-touch-icon" type="image/ico" sizes="64x64" href="favicon.ico">

    <meta charset="utf-8">
    <title>{{$config->title}}</title>

    <link rel="stylesheet" href="/design/default/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.10/css/all.css"
          integrity="sha384-+d0P83n9kaQMCwj8F4RJB66tzIwOKmrdb46+porD/OvrJ+37WqIM7UoBtwHO6Nlg"
          crossorigin="anonymous">
    <link rel="stylesheet" href="/design/default/css/style.css">

    <style>{{echo App\Hook::apply('head.style')}}</style>
    <script>{{ echo App\Hook:: apply('head.script') }}</script>
</head>

<body>

    <div class="container loading mt-3">
        {{echo App\Hook::apply('before.content')}}

        {{if (isset($_SESSION['message'])):}}
        <div class="row mt-3">
            <div class="col">
                <div class="alert alert-{{$_SESSION['message']['class']}}" role="alert">
                    <button type="button" class="close" data-dismiss="alert"
                            aria-label="close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                    {{$_SESSION['message']['text']}}
                </div>
            </div>
        </div>
        {{unset($_SESSION['message'])}}
        {{endif}}

        {{include 'design_cpl/' . $config->design . '.' . $page . '.html'}}

        {{echo App\Hook::apply('after.content')}}
    </div>

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="/design/default/js/bootstrap.bundle.min.js"></script>
    <script src="/design/default/js/script.js"></script>
    {{echo App\Hook::apply('body.script')}}

</body>

</html>
